package com.lifescore.app.presentation.ui.wellness

import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.lifescore.app.presentation.ui.screentime.ScreenTimeViewModel

// ==========================================
// 1. TASK BREAKTHROUGH (AI 3-Priority Decomposer)
// ==========================================
data class SubPriorityStep(
    val stepNumber: Int,
    val title: String,
    val minutes: Int,
    val isDone: Boolean = false
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TaskBreakthroughScreen(
    onBack: () -> Unit = {}
) {
    var rawAssignment by remember { mutableStateOf("") }
    var isDecomposing by remember { mutableStateOf(false) }
    var breakdownSteps by remember {
        mutableStateOf(
            listOf(
                SubPriorityStep(1, "Clarify Core Requirements & Create 1-Page Outline", 15),
                SubPriorityStep(2, "Draft 3 Core Arguments / Skeleton Functions", 25),
                SubPriorityStep(3, "Polish & Verification Test", 10)
            )
        )
    }
    var hasGenerated by remember { mutableStateOf(true) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("⚡ Task Breakthrough", fontWeight = FontWeight.Bold)
                        Text(
                            "AI 3-Priority Decomposer • Beats Overwhelm",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            Card(
                shape = RoundedCornerShape(16.dp),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text(
                        "Enter your intimidating task or assignment:",
                        fontWeight = FontWeight.Bold,
                        style = MaterialTheme.typography.bodyMedium
                    )
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = rawAssignment,
                        onValueChange = { rawAssignment = it },
                        placeholder = { Text("e.g., Complete 20-page research thesis literature review") },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        minLines = 2
                    )
                    Spacer(Modifier.height(12.dp))
                    Button(
                        onClick = {
                            isDecomposing = true
                            hasGenerated = true
                            isDecomposing = false
                        },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(10.dp)
                    ) {
                        Icon(Icons.Default.Star, contentDescription = null)
                        Spacer(Modifier.width(8.dp))
                        Text("Break Down into 3 High-Impact Steps (+30 XP)")
                    }
                }
            }

            if (hasGenerated) {
                Text(
                    "🎯 Your 3 Non-Negotiable Priorities",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold
                )

                breakdownSteps.forEachIndexed { index, step ->
                    Card(
                        shape = RoundedCornerShape(16.dp),
                        colors = CardDefaults.cardColors(
                            containerColor = if (step.isDone) MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.4f) else MaterialTheme.colorScheme.surface
                        ),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(16.dp),
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.weight(1f)) {
                                Box(
                                    contentAlignment = Alignment.Center,
                                    modifier = Modifier
                                        .size(32.dp)
                                        .clip(CircleShape)
                                        .background(MaterialTheme.colorScheme.primaryContainer)
                                ) {
                                    Text("${step.stepNumber}", fontWeight = FontWeight.Black, color = MaterialTheme.colorScheme.primary)
                                }
                                Spacer(Modifier.width(12.dp))
                                Column {
                                    Text(
                                        step.title,
                                        fontWeight = FontWeight.SemiBold,
                                        style = MaterialTheme.typography.bodyMedium
                                    )
                                    Text(
                                        "⏱️ ~${step.minutes} mins",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant
                                    )
                                }
                            }

                            Checkbox(
                                checked = step.isDone,
                                onCheckedChange = { isChecked ->
                                    breakdownSteps = breakdownSteps.toMutableList().also {
                                        it[index] = step.copy(isDone = isChecked)
                                    }
                                }
                            )
                        }
                    }
                }
            }
        }
    }
}

// ==========================================
// 2. THOUGHT BREAK (CBT Cognitive Reframing)
// ==========================================
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ThoughtBreakScreen(
    viewModel: ScreenTimeViewModel,
    onBack: () -> Unit = {}
) {
    var automaticThought by remember { mutableStateOf("") }
    var selectedDistortion by remember { mutableStateOf("Catastrophizing") }
    var evidenceAgainst by remember { mutableStateOf("") }
    var reframedThought by remember { mutableStateOf("") }
    var reliefRating by remember { mutableStateOf(8f) }
    var isSubmitted by remember { mutableStateOf(false) }

    val distortions = listOf(
        "Catastrophizing",
        "All-or-Nothing",
        "Mind Reading",
        "Emotional Reasoning",
        "Overgeneralizing"
    )

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("🧠 Thought Break", fontWeight = FontWeight.Bold)
                        Text(
                            "CBT Cognitive Reframing • Break Stuck Loops",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back")
                    }
                }
            )
        }
    ) { padding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            item {
                Card(
                    shape = RoundedCornerShape(18.dp),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.5f))
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("1. What automatic negative thought is bothering you?", fontWeight = FontWeight.Bold)
                        Spacer(Modifier.height(8.dp))
                        OutlinedTextField(
                            value = automaticThought,
                            onValueChange = { automaticThought = it },
                            placeholder = { Text("e.g., 'If I don't finish this perfectly today, my entire project will fail.'") },
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp),
                            minLines = 2
                        )
                    }
                }
            }

            item {
                Text("2. Identify the Cognitive Distortion:", fontWeight = FontWeight.Bold)
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    distortions.take(3).forEach { dist ->
                        FilterChip(
                            selected = selectedDistortion == dist,
                            onClick = { selectedDistortion = dist },
                            label = { Text(dist, fontSize = 12.sp) }
                        )
                    }
                }
            }

            item {
                Card(
                    shape = RoundedCornerShape(18.dp),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("3. Evidence against this thought:", fontWeight = FontWeight.Bold)
                        Spacer(Modifier.height(8.dp))
                        OutlinedTextField(
                            value = evidenceAgainst,
                            onValueChange = { evidenceAgainst = it },
                            placeholder = { Text("e.g., I've made steady progress every day. Iteration matters more than immediate perfection.") },
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp),
                            minLines = 2
                        )
                    }
                }
            }

            item {
                Card(
                    shape = RoundedCornerShape(18.dp),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("4. Balanced & Empowering Reframe:", fontWeight = FontWeight.Bold)
                        Spacer(Modifier.height(8.dp))
                        OutlinedTextField(
                            value = reframedThought,
                            onValueChange = { reframedThought = it },
                            placeholder = { Text("e.g., 'I will focus on one clean step today. Progress is compound, not instantaneous.'") },
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp),
                            minLines = 2
                        )
                        Spacer(Modifier.height(12.dp))
                        Text("Emotional Relief: ${reliefRating.toInt()} / 10", style = MaterialTheme.typography.bodySmall)
                        Slider(
                            value = reliefRating,
                            onValueChange = { reliefRating = it },
                            valueRange = 1f..10f,
                            steps = 9
                        )
                        Spacer(Modifier.height(8.dp))
                        Button(
                            onClick = {
                                viewModel.submitThoughtBreak(
                                    automaticThought.ifBlank { "Unexamined friction thought" },
                                    selectedDistortion,
                                    evidenceAgainst.ifBlank { "Evidence of past capability" },
                                    reframedThought.ifBlank { "Balanced realistic perspective" },
                                    reliefRating.toInt()
                                )
                                isSubmitted = true
                            },
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp)
                        ) {
                            Icon(Icons.Default.Check, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text("Save Reframe (+40 XP Mental Health)")
                        }
                    }
                }
            }
        }
    }
}
