package com.lifescore.app.presentation.navigation

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.MenuBook
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.vector.ImageVector

sealed class Screen(val route: String, val title: String, val icon: ImageVector) {
    object Home : Screen("home", "Home", Icons.Default.Home)
    object Dimensions : Screen("dimensions", "Dimensions", Icons.Default.PieChart)
    object Tasks : Screen("tasks", "Quests", Icons.Default.Checklist)
    object Challenges : Screen("challenges", "Challenges", Icons.Default.EmojiEvents)
    object AICoach : Screen("ai_coach", "AI Coach", Icons.Default.Psychology)
    object Leaderboard : Screen("leaderboard", "Ranks", Icons.Default.Leaderboard)
    object MicroVlogs : Screen("micro_vlogs", "Reels", Icons.Default.Videocam)
    object ArchetypeProfile : Screen("archetype_profile", "Archetype", Icons.Default.Shield)
    object SkillMastery : Screen("skill_mastery", "Mastery", Icons.Default.Timer)
    object RewardStore : Screen("reward_store", "Store", Icons.Default.ShoppingBag)
    object Enterprise : Screen("enterprise", "Enterprise", Icons.Default.Business)
    object Profile : Screen("profile", "Profile", Icons.Default.AccountCircle)
    object MemeStudio : Screen("meme_studio", "Memes", Icons.Default.AutoAwesomeMotion)
    object Settings : Screen("settings", "Settings", Icons.Default.Settings)
    object Consent : Screen("consent", "Consent", Icons.Default.Security)
    object Onboarding : Screen("onboarding", "Assessment", Icons.Default.AutoAwesome)
    object Login : Screen("login", "Login", Icons.Default.Lock)
    object AiQuests : Screen("ai_quests", "AI Quests", Icons.Default.AutoAwesome)
    object CharacterStats : Screen("character_stats", "Stats", Icons.Default.Shield)
    object GroupHabits : Screen("group_habits", "Squads", Icons.Default.Group)
    object Journal : Screen("journal", "Journal", Icons.Default.Book)
    object Combat : Screen("combat", "Raids", Icons.Default.FlashOn)
    object Analytics : Screen("analytics", "Analytics", Icons.Default.BarChart)
    object Privacy : Screen("privacy", "Privacy", Icons.Default.Lock)
    object HabitLibrary : Screen("habit_library", "100 Habits", Icons.Default.ListAlt)
    object ActionPlan : Screen("action_plan", "Action Plan", Icons.Default.TrackChanges)
    object Hydration : Screen("hydration", "Hydration", Icons.Default.WaterDrop)
    object TrackerHub : Screen("tracker_hub", "15 Trackers", Icons.Default.DashboardCustomize)
    object AtomicHabits : Screen("atomic_habits", "Atomic Habits", Icons.Default.Bolt)
    object Recovery : Screen("recovery", "Addiction Recovery", Icons.Default.HealthAndSafety)
    object RecoverySos : Screen("recovery_sos", "Craving SOS", Icons.Default.Warning)
    object BookLibrary : Screen("book_library", "Book Summaries", Icons.AutoMirrored.Filled.MenuBook)
    object DailyGrowth : Screen("daily_growth", "15-Min Growth", Icons.Default.Lightbulb)
    object FocusTimer : Screen("focus_timer", "Mindful Focus", Icons.Default.Timer)
    object MoodTracker : Screen("mood_tracker", "Mood Tracker", Icons.Default.Mood)
    object SleepSoundscapes : Screen("sleep_soundscapes", "Sleep & Sounds", Icons.Default.Bedtime)
    object ScreenTime : Screen("screen_time", "Screen Time & Detox", Icons.Default.PhoneAndroid)
    object MinimalistLauncher : Screen("minimalist_launcher", "Minimalist Mode", Icons.Default.FilterNone)
    object TaskBreakthrough : Screen("task_breakthrough", "Task Breakthrough", Icons.Default.Bolt)
    object ThoughtBreak : Screen("thought_break", "Thought Break", Icons.Default.Psychology)
    object BookFlashcards : Screen("book_flashcards", "Flashcards & Plans", Icons.Default.School)
    object EnergySchedule : Screen("energy_schedule", "Energy-Aware Schedule", Icons.Default.ElectricBolt)
    object VirtualPet : Screen("virtual_pet", "Virtual Pet Companion", Icons.Default.Pets)
    object MeditationLibrary : Screen("meditation_library", "Insight Meditation", Icons.Default.SelfImprovement)
    object PartySystem : Screen("party_system", "RPG Party & Quests", Icons.Default.Shield)
    object CoachMarketplace : Screen("coach_marketplace", "Coach Marketplace", Icons.Default.SupportAgent)
    object NeurodivergentHub : Screen("neurodivergent_hub", "Soft Focus ADHD Hub", Icons.Default.Visibility)
    object ScienceJourneys : Screen("science_journeys", "Science Journeys", Icons.Default.Biotech)
    object ViralReferrals : Screen("viral_referrals", "Invite Friends & Free Premium", Icons.Default.CardGiftcard)
    object LeagueTiers : Screen("league_tiers", "10-Tier Leagues", Icons.Default.EmojiEvents)
    object StreakVault : Screen("streak_vault", "Streak Vault & Protection", Icons.Default.Shield)
    object CustomRewards : Screen("custom_rewards", "Custom Gold Rewards Store", Icons.Default.MonetizationOn)
    object FriendsFeed : Screen("friends_feed", "Friends Social Feed", Icons.Default.Group)
    object AiMemoryInspector : Screen("ai_memory_inspector", "AI Memory & Coaching", Icons.Default.Psychology)
}
